---
- name: this playbook install the httpd
  hosts: appservers
  become: true
  tasks:
  - name: update apt cache
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: install package
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
        
  - name: install package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "RedHat"



