---
- name: This playbook installs the httpd
  hosts: all
  become: true
  tasks:
  - name: install package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install package
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: start the service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: start the service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

